spring.application.name=VaultyCash
spring.datasource.url=jdbc:postgresql://ep-rough-block-atqwv7hk.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_v3SxDBFPkA8C

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
